
package Views;


import Controller.ControladorAuditoriasMenuIFrame;

/**
 *
 * @author david
 */
public class AuditoriasMenuIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form HerramientasMenuIFrame
     */
    public AuditoriasMenuIFrame() {
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        verAuditorias = new javax.swing.JLabel();
        generarAuditorias = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Menú herramientas");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Menú auditorias");

        verAuditorias.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        verAuditorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verAuditorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_archive_list_of_parts_80px.png"))); // NOI18N
        verAuditorias.setText("Ver auditorias");
        verAuditorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        generarAuditorias.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        generarAuditorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_test_passed_80px.png"))); // NOI18N
        generarAuditorias.setText("Generar auditorias");
        generarAuditorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verAuditorias, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(titulo)
                            .addGap(442, 442, 442))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(generarAuditorias, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(416, 416, 416)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(135, 135, 135)
                .addComponent(generarAuditorias, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(verAuditorias, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel generarAuditorias;
    private javax.swing.JLabel titulo;
    public javax.swing.JLabel verAuditorias;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorAuditoriasMenuIFrame controladorAuditoriasMenuIFrame = new ControladorAuditoriasMenuIFrame(this);
        generarAuditorias.addMouseListener(controladorAuditoriasMenuIFrame);
        verAuditorias.addMouseListener(controladorAuditoriasMenuIFrame);
    }
}
