
package Views;


import Controller.ControladorCambiarContrasenaIFrame;

/**
 *
 * @author david
 */
public class CambiarContrasenaIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form HerramientasMenuIFrame
     */
    public CambiarContrasenaIFrame() {
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        txtTipoUsuario = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        aceptar = new javax.swing.JLabel();
        txtTipoUsuario1 = new javax.swing.JLabel();
        txtTipoUsuario2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contrasenaNueva = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        mostrarContrasenaNueva = new javax.swing.JLabel();
        ocultarContrasenaNueva = new javax.swing.JLabel();
        ocultarContrasenaNueva.setVisible(false);
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        contrasenaActual = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        mostrarContrasenaActual = new javax.swing.JLabel();
        ocultarContrasenaActual = new javax.swing.JLabel();
        ocultarContrasenaActual.setVisible(false);
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        contrasenaConfirmar = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        mostrarContrasenaConfirmar = new javax.swing.JLabel();
        ocultarContrasenaConfirmar = new javax.swing.JLabel();
        ocultarContrasenaConfirmar.setVisible(false);

        setClosable(true);
        setTitle("Menú herramientas");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Cambiar contraseña");

        txtTipoUsuario.setFont(new java.awt.Font("Axia", 2, 36)); // NOI18N
        txtTipoUsuario.setText("Confirmar contraseña:");

        cancelar.setBackground(new java.awt.Color(96, 133, 188));
        cancelar.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("Cancelar");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelar.setOpaque(true);

        aceptar.setBackground(new java.awt.Color(96, 133, 188));
        aceptar.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceptar.setText("Aceptar");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aceptar.setOpaque(true);

        txtTipoUsuario1.setFont(new java.awt.Font("Axia", 2, 36)); // NOI18N
        txtTipoUsuario1.setText("Contraseña actual:");

        txtTipoUsuario2.setFont(new java.awt.Font("Axia", 2, 36)); // NOI18N
        txtTipoUsuario2.setText("Contraseña nueva:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_lock_25px_1.png"))); // NOI18N

        contrasenaNueva.setBackground(new java.awt.Color(238, 238, 238));
        contrasenaNueva.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        contrasenaNueva.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarContrasenaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_eye_25px.png"))); // NOI18N
        mostrarContrasenaNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.add(mostrarContrasenaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        ocultarContrasenaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_hide_25px.png"))); // NOI18N
        ocultarContrasenaNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.add(ocultarContrasenaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasenaNueva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jSeparator2)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_lock_25px_1.png"))); // NOI18N

        contrasenaActual.setBackground(new java.awt.Color(238, 238, 238));
        contrasenaActual.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        contrasenaActual.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarContrasenaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_eye_25px.png"))); // NOI18N
        mostrarContrasenaActual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(mostrarContrasenaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        ocultarContrasenaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_hide_25px.png"))); // NOI18N
        ocultarContrasenaActual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(ocultarContrasenaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasenaActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jSeparator3)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_lock_25px_1.png"))); // NOI18N

        contrasenaConfirmar.setBackground(new java.awt.Color(238, 238, 238));
        contrasenaConfirmar.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        contrasenaConfirmar.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarContrasenaConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_eye_25px.png"))); // NOI18N
        mostrarContrasenaConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.add(mostrarContrasenaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        ocultarContrasenaConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_hide_25px.png"))); // NOI18N
        ocultarContrasenaConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.add(ocultarContrasenaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, -1, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasenaConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jSeparator4)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasenaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTipoUsuario1)
                            .addComponent(txtTipoUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo)
                .addGap(64, 64, 64)
                .addComponent(txtTipoUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTipoUsuario)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel aceptar;
    public javax.swing.JLabel cancelar;
    public javax.swing.JPasswordField contrasenaActual;
    public javax.swing.JPasswordField contrasenaConfirmar;
    public javax.swing.JPasswordField contrasenaNueva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel mostrarContrasenaActual;
    public javax.swing.JLabel mostrarContrasenaConfirmar;
    public javax.swing.JLabel mostrarContrasenaNueva;
    public javax.swing.JLabel ocultarContrasenaActual;
    public javax.swing.JLabel ocultarContrasenaConfirmar;
    public javax.swing.JLabel ocultarContrasenaNueva;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtTipoUsuario;
    private javax.swing.JLabel txtTipoUsuario1;
    private javax.swing.JLabel txtTipoUsuario2;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorCambiarContrasenaIFrame controladorCambiarContrasenaIFrame = new ControladorCambiarContrasenaIFrame(this);
        mostrarContrasenaActual.addMouseListener(controladorCambiarContrasenaIFrame);
        ocultarContrasenaActual.addMouseListener(controladorCambiarContrasenaIFrame);
        mostrarContrasenaNueva.addMouseListener(controladorCambiarContrasenaIFrame);
        ocultarContrasenaNueva.addMouseListener(controladorCambiarContrasenaIFrame);
        mostrarContrasenaConfirmar.addMouseListener(controladorCambiarContrasenaIFrame);
        ocultarContrasenaConfirmar.addMouseListener(controladorCambiarContrasenaIFrame);
        aceptar.addMouseListener(controladorCambiarContrasenaIFrame);
        cancelar.addMouseListener(controladorCambiarContrasenaIFrame);
    }
}
