/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controller.ControladorEmpleadosMenuIFrame;

/**
 *
 * @author david
 */
public class EmpleadosMenuIFrame extends javax.swing.JInternalFrame {
    private final VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form EmpleadosMenuIFrame
     */
    public EmpleadosMenuIFrame(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        rEmpleados = new javax.swing.JLabel();
        verEmpleados = new javax.swing.JLabel();
        rUsuarios = new javax.swing.JLabel();
        verUsuarios = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Menú empleados");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Menú empleados");

        rEmpleados.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        rEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_worker_80px.png"))); // NOI18N
        rEmpleados.setText("Registrar Empleados");
        rEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        verEmpleados.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        verEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_workers_80px.png"))); // NOI18N
        verEmpleados.setText("Ver empleados");
        verEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rUsuarios.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        rUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_user_male_80px_2.png"))); // NOI18N
        rUsuarios.setText("Registrar usuarios");
        rUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        verUsuarios.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        verUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_group_80px.png"))); // NOI18N
        verUsuarios.setText("Ver usuarios");
        verUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(420, 420, 420))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(verUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rEmpleados))
                .addGap(71, 71, 71))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(rUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(711, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo)
                .addGap(86, 86, 86)
                .addComponent(rEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(rUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(610, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel rEmpleados;
    public javax.swing.JLabel rUsuarios;
    private javax.swing.JLabel titulo;
    public javax.swing.JLabel verEmpleados;
    public javax.swing.JLabel verUsuarios;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorEmpleadosMenuIFrame controladorEmpleadosMenuIFrame = new ControladorEmpleadosMenuIFrame(this,ventanaPrincipal);
        rEmpleados.addMouseListener(controladorEmpleadosMenuIFrame);
        rUsuarios.addMouseListener(controladorEmpleadosMenuIFrame);
        verEmpleados.addMouseListener(controladorEmpleadosMenuIFrame);
        verUsuarios.addMouseListener(controladorEmpleadosMenuIFrame);
    }
}
