/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controller.ControladorHerramientasMenuIFrame;

/**
 *
 * @author david
 */
public class HerramientasMenuIFrame extends javax.swing.JInternalFrame {
    private final VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form HerramientasMenuIFrame
     */
    public HerramientasMenuIFrame(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        prestarHerramientas = new javax.swing.JLabel();
        solicitarHerramientas = new javax.swing.JLabel();
        rHerramientas = new javax.swing.JLabel();
        verHerramientas = new javax.swing.JLabel();
        registrarTHerramienta = new javax.swing.JLabel();
        registrarTComponente = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Menú herramientas");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Menú herramientas");

        prestarHerramientas.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        prestarHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_check_document_80px.png"))); // NOI18N
        prestarHerramientas.setText("Prestar herramientas");
        prestarHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        solicitarHerramientas.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        solicitarHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Maintenance_80px.png"))); // NOI18N
        solicitarHerramientas.setText("Solicitar herramientas");
        solicitarHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rHerramientas.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        rHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_80px.png"))); // NOI18N
        rHerramientas.setText("Registrar herramientas");
        rHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        verHerramientas.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        verHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Tools_80px.png"))); // NOI18N
        verHerramientas.setText("Ver herramientas");
        verHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        registrarTHerramienta.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        registrarTHerramienta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Full_Tool_Storage_Box_80px.png"))); // NOI18N
        registrarTHerramienta.setText("Registrar tipo herramienta");
        registrarTHerramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        registrarTComponente.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        registrarTComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_crane_hook_80px.png"))); // NOI18N
        registrarTComponente.setText("Registrar tipo componente");
        registrarTComponente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 447, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(403, 403, 403))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrarTHerramienta)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rHerramientas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solicitarHerramientas)
                            .addComponent(prestarHerramientas))
                        .addGap(87, 87, 87))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(757, Short.MAX_VALUE)
                    .addComponent(registrarTComponente)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prestarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solicitarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarTHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(699, Short.MAX_VALUE)
                    .addComponent(registrarTComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel prestarHerramientas;
    public javax.swing.JLabel rHerramientas;
    public javax.swing.JLabel registrarTComponente;
    public javax.swing.JLabel registrarTHerramienta;
    public javax.swing.JLabel solicitarHerramientas;
    private javax.swing.JLabel titulo;
    public javax.swing.JLabel verHerramientas;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorHerramientasMenuIFrame controladorHerramientasMenuIFrame = new ControladorHerramientasMenuIFrame(this,ventanaPrincipal);
        prestarHerramientas.addMouseListener(controladorHerramientasMenuIFrame);
        rHerramientas.addMouseListener(controladorHerramientasMenuIFrame);
        solicitarHerramientas.addMouseListener(controladorHerramientasMenuIFrame);
        verHerramientas.addMouseListener(controladorHerramientasMenuIFrame);
        registrarTComponente.addMouseListener(controladorHerramientasMenuIFrame);
        registrarTHerramienta.addMouseListener(controladorHerramientasMenuIFrame);
    }
}
