
package Views;


import Controller.ControladorPerfilMenuIFrame;

/**
 *
 * @author david
 */
public class PerfilMenuIFrame extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form HerramientasMenuIFrame
     */
    private final VentanaPrincipal ventanaPrincipal;
    public PerfilMenuIFrame(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        imgn = new javax.swing.JLabel();
        txtTipoUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        cambiarContrasena = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Menú herramientas");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Mi perfil");

        imgn.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        imgn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgnPerfil.png"))); // NOI18N
        imgn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtTipoUsuario.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        txtTipoUsuario.setText("Tipo usuario");

        lblNombre.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        lblNombre.setText("Nombre:");

        lblUsuario.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        lblUsuario.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtUsuario.setText("Nombre de usuario.");

        txtNombre.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtNombre.setText("Nombre completo.");

        cambiarContrasena.setBackground(new java.awt.Color(96, 133, 188));
        cambiarContrasena.setFont(new java.awt.Font("Axia", 3, 24)); // NOI18N
        cambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        cambiarContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiarContrasena.setText("Cambiar contraseña");
        cambiarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiarContrasena.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imgn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblNombre))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtTipoUsuario)))
                        .addGap(377, 377, 377))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(535, 535, 535))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titulo)
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(txtUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(txtTipoUsuario))
                    .addComponent(imgn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(cambiarContrasena)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cambiarContrasena;
    private javax.swing.JLabel imgn;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTipoUsuario;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorPerfilMenuIFrame controladorPerfilMenuIFrame = new ControladorPerfilMenuIFrame(this, ventanaPrincipal);
        cambiarContrasena.addMouseListener(controladorPerfilMenuIFrame);
    }
}
