package Views;


import Controller.ControladorRegistroTipoHerramientasIFrame;

/**
 *
 * @author david
 */
public class RegistroTipoHerramientasIFrame extends javax.swing.JInternalFrame {

    private final VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form VerEmpleadosIFrame
     */
    public RegistroTipoHerramientasIFrame(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloTipoHerramienta = new javax.swing.JLabel();
        lblNombreTipoHerr = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreTipoHerramienta = new javax.swing.JTextField();
        btnGuardarTipo = new javax.swing.JLabel();
        lblNombreTipoHerr1 = new javax.swing.JLabel();
        txtBuscarTipoHerramienta = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnBuscarTipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Registro de tipo de herramienta");

        lblTituloTipoHerramienta.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        lblTituloTipoHerramienta.setText("Registro de tipo de herramientas");

        lblNombreTipoHerr.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        lblNombreTipoHerr.setText("Nombre:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtNombreTipoHerramienta.setBackground(new java.awt.Color(238, 238, 238));
        txtNombreTipoHerramienta.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtNombreTipoHerramienta.setBorder(null);

        btnGuardarTipo.setBackground(new java.awt.Color(96, 133, 188));
        btnGuardarTipo.setFont(new java.awt.Font("Axia", 3, 36)); // NOI18N
        btnGuardarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarTipo.setText("Guardar");
        btnGuardarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarTipo.setOpaque(true);

        lblNombreTipoHerr1.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        lblNombreTipoHerr1.setText("Lista de tipos de herramientas");

        txtBuscarTipoHerramienta.setBackground(new java.awt.Color(238, 238, 238));
        txtBuscarTipoHerramienta.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtBuscarTipoHerramienta.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscarTipo.setBackground(new java.awt.Color(96, 133, 188));
        btnBuscarTipo.setFont(new java.awt.Font("Axia", 3, 24)); // NOI18N
        btnBuscarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarTipo.setText("Buscar");
        btnBuscarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarTipo.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre del tipo de herramienta "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblNombreTipoHerr1)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarTipoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreTipoHerr)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(txtNombreTipoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloTipoHerramienta)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTituloTipoHerramienta)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTipoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreTipoHerr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnGuardarTipo)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtBuscarTipoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblNombreTipoHerr1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnBuscarTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnBuscarTipo;
    public javax.swing.JLabel btnGuardarTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombreTipoHerr;
    private javax.swing.JLabel lblNombreTipoHerr1;
    private javax.swing.JLabel lblTituloTipoHerramienta;
    public javax.swing.JTextField txtBuscarTipoHerramienta;
    public javax.swing.JTextField txtNombreTipoHerramienta;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorRegistroTipoHerramientasIFrame controladorRegistroTipoHerramientasIFrame = new ControladorRegistroTipoHerramientasIFrame(this);
        btnGuardarTipo.addMouseListener(controladorRegistroTipoHerramientasIFrame);
        btnBuscarTipo.addMouseListener(controladorRegistroTipoHerramientasIFrame);
    }
}
