package Views;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author david
 */
public class RegistroComputadoras extends javax.swing.JInternalFrame {
    private final VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form VerEmpleadosIFrame
     */
    public RegistroComputadoras(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSEALPATH = new javax.swing.ButtonGroup();
        btnGroupSEFE = new javax.swing.ButtonGroup();
        btnGroupSMP = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        txtMarcaModelo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtNserie = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        txtComentarios.setLineWrap(true);
        txtComentarios.setWrapStyleWord(true);

        JScrollPane scrollPaneComentarios = new JScrollPane(txtComentarios);
        scrollPaneComentarios.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPaneComentarios.setPreferredSize(new Dimension(150,50));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSiSealpath = new javax.swing.JRadioButton();
        btnNoSealpath = new javax.swing.JRadioButton();
        btnNoSmp = new javax.swing.JRadioButton();
        btnSiSmp = new javax.swing.JRadioButton();
        btnNoSefe = new javax.swing.JRadioButton();
        btnSiSefe = new javax.swing.JRadioButton();
        guardar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Registrar computadoras portatiles");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Registro de computadoras");

        txtMarcaModelo.setBackground(new java.awt.Color(238, 238, 238));
        txtMarcaModelo.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtMarcaModelo.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel1.setText("Marca/Modelo:");

        txtNserie.setBackground(new java.awt.Color(238, 238, 238));
        txtNserie.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtNserie.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel2.setText("Software SEFE :");

        txtComentarios.setBackground(new java.awt.Color(238, 238, 238));
        txtComentarios.setColumns(20);
        txtComentarios.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        txtComentarios.setRows(5);
        txtComentarios.setBorder(null);
        txtComentarios.setPreferredSize(new java.awt.Dimension(392, 149));
        jScrollPane1.setViewportView(txtComentarios);

        jLabel3.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel3.setText("Comentarios:");

        jLabel4.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel4.setText("N° de serie:");

        jLabel5.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel5.setText("Software SMP :");

        jLabel6.setFont(new java.awt.Font("Axia", 0, 24)); // NOI18N
        jLabel6.setText("Software SEALPATH :");

        btnGroupSEALPATH.add(btnSiSealpath);
        btnSiSealpath.setText("Si");
        btnSiSealpath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGroupSEALPATH.add(btnNoSealpath);
        btnNoSealpath.setText("No");
        btnNoSealpath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGroupSMP.add(btnNoSmp);
        btnNoSmp.setText("No");
        btnNoSmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGroupSMP.add(btnSiSmp);
        btnSiSmp.setText("Si");
        btnSiSmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGroupSEFE.add(btnNoSefe);
        btnNoSefe.setText("No");

        btnGroupSEFE.add(btnSiSefe);
        btnSiSefe.setText("Si");

        guardar.setBackground(new java.awt.Color(96, 133, 188));
        guardar.setFont(new java.awt.Font("Axia", 3, 24)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardar.setText("Guardar");
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(titulo)
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMarcaModelo)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNserie)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))))
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSiSefe)
                                .addGap(18, 18, 18)
                                .addComponent(btnNoSefe))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSiSmp)
                                .addGap(18, 18, 18)
                                .addComponent(btnNoSmp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiSealpath)
                                .addGap(18, 18, 18)
                                .addComponent(btnNoSealpath)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jLabel4)
                    .addContainerGap(940, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(btnSiSefe)
                        .addComponent(btnNoSefe)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(btnSiSealpath)
                        .addComponent(btnNoSealpath)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(btnSiSmp)
                        .addComponent(btnNoSmp))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(guardar)
                .addGap(97, 97, 97))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(367, 367, 367)
                    .addComponent(jLabel4)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSEALPATH;
    private javax.swing.ButtonGroup btnGroupSEFE;
    private javax.swing.ButtonGroup btnGroupSMP;
    private javax.swing.JRadioButton btnNoSealpath;
    private javax.swing.JRadioButton btnNoSefe;
    private javax.swing.JRadioButton btnNoSmp;
    private javax.swing.JRadioButton btnSiSealpath;
    private javax.swing.JRadioButton btnSiSefe;
    private javax.swing.JRadioButton btnSiSmp;
    public javax.swing.JLabel guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtMarcaModelo;
    private javax.swing.JTextField txtNserie;
    // End of variables declaration//GEN-END:variables
}
