
package Views;


import Controller.ControladorReportesMenuIFrame;

/**
 *
 * @author david
 */
public class ReportesMenuIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form HerramientasMenuIFrame
     */
    public ReportesMenuIFrame() {
        initComponents();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        generarPDF = new javax.swing.JLabel();
        verReportes = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Menú herramientas");

        titulo.setFont(new java.awt.Font("Axia", 3, 48)); // NOI18N
        titulo.setText("Menú reportes");

        generarPDF.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        generarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_export_pdf_80px_1.png"))); // NOI18N
        generarPDF.setText("Generar PDF");
        generarPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        verReportes.setFont(new java.awt.Font("Axia", 0, 36)); // NOI18N
        verReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_archive_list_of_parts_80px.png"))); // NOI18N
        verReportes.setText("Ver reportes");
        verReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(verReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 729, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generarPDF)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(442, 442, 442))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(361, 361, 361))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel generarPDF;
    private javax.swing.JLabel titulo;
    public javax.swing.JLabel verReportes;
    // End of variables declaration//GEN-END:variables

    private void addListeners(){
        ControladorReportesMenuIFrame controladorReportesMenuIFrame = new ControladorReportesMenuIFrame(this);
        generarPDF.addMouseListener(controladorReportesMenuIFrame);
        verReportes.addMouseListener(controladorReportesMenuIFrame);
    }
}
